# Generated by Django 5.0.1 on 2024-01-29 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('organisation_id', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('organisation_name', models.CharField(max_length=180)),
                ('onboarding_status', models.CharField(choices=[('onboarding_incomplete', 'onboarding_incomplete'), ('verification_pending', 'verification_pending'), ('verification_queried', 'verification_queried'), ('onboarding_complete', 'onboarding_complete')], max_length=25)),
                ('organisation_registered', models.BooleanField(default=False)),
                ('organisation_reg_number', models.TextField()),
                ('organisation_email', models.EmailField(max_length=254)),
                ('organisation_phone', models.IntegerField()),
                ('organisation_website', models.URLField()),
                ('contact_name', models.TextField()),
                ('contact_phone', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_email_verified', models.BooleanField(default=False)),
                ('access_status', models.TextField()),
            ],
        ),
    ]
