# Generated by Django 5.0.1 on 2024-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organisation_phone',
            field=models.CharField(max_length=20),
        ),
    ]
