# Generated by Django 5.0.1 on 2024-02-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizationinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvite',
            name='slug',
            field=models.SlugField(default='3d9l19y'),
        ),
    ]
