# Generated by Django 5.0.1 on 2024-01-23 23:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField()),
                ('password', models.CharField(max_length=128)),
                ('organisation', models.TextField()),
                ('organisation_role', models.TextField()),
                ('onboarding_status', models.TextField()),
            ],
        ),
    ]
